[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/mail/artisan queue:work --sleep=3 --tries=3 --max-time=3600
directory=/var/www/mail
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=4
redirect_stderr=true
stdout_logfile=/var/log/supervisor/laravel-worker.log
stopwaitsecs=3600

[program:laravel-reverb]
process_name=%(program_name)s
command=php /var/www/mail/artisan reverb:start --host=0.0.0.0 --port=8080
directory=/var/www/mail
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/laravel-reverb.log
